const words = {
  tr: {
    TreatmentPlaningSteps: {
      1: 'İhtiyacını Seç',
      2: 'Lokasyon Seç',
      3: 'Klinik Seç',
      4: 'Hekim Seç',
      5: 'Tarih Seç',
      6: 'Tedavi Talebi Onayı',
      7: 'Sonuç',
    },
    selectTreatment: 'Tedavi Seç',
    consultDoctor: 'Hekime Danış',
    or: 'veya',
    more: 'devamı',
    select: 'seç',
    showLess: 'Daha az göster',
    clinicConsultation: 'klinikte Görüş',
    onlineConsultation: 'Online Görüş',
    review: 'Değerlendirmele',
    price: 'Fiyat',
    avgPrice: 'Fiyat Aralığı',
    today: 'Bugün',
    tomorrow: 'yarın',
    home: 'Anasayfa',
    favorites: 'Favorilerim',
    appointment: 'Randevulrım',
    orders: 'Siprislerim',
    profile: 'Profil',

    myComments: 'Yorumlarım',
    myCards: 'Kredi Kartlarım',
    myOrders: 'Siparişlerim',
    myPrescriptions: 'Reçetelerim',
    myXRays: 'Fotoğraflarım Röntgenlerim',
    myQandA: 'Sorularım ve Cevaplarım',
    myInfo: 'Kişisel Bilgilerim',
  },

  en: {
    TreatmentPlaningSteps: {
      1: 'Choose Your Need',
      2: 'Select Location',
      3: 'Choose Clinic',
      4: 'Choose Physician',
      5: 'Select Date',
      6: 'Treatment Request Approval',
      7: 'Request Summary',
    },
    selectTreatment: 'Select a Treatment',
    consultDoctor: 'Consult a Physician',
    or: 'or',
    more: 'more',
    select: 'select',
    showLess: 'show less',
    clinicConsultation: 'Consultation at the Clinic',
    onlineConsultation: 'Online Consultation',
    review: 'Reviews',
    price: 'Price',
    avgPrice: 'Average wPrice',
    today: 'Today',
    tomorrow: 'Tomorrow',
    home: 'Home',
    favorites: 'Favorites',
    appointment: 'Appointment',
    orders: 'Orders',
    profile: 'Profile',
    myComments: 'My Comments',
    myCards: 'My Credit Cards',
    myOrders: 'My Orders',
    myPrescriptions: 'My Prescriptions',
    myXRays: 'My X-Rays Photos',
    myQandA: 'My Questions and Answers',
    myInfo: 'My Presonal Information',
  },
};

export default words;
